version: "3.0"
services:
  nginx:
    image: library/nginx:1.19
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx
      - ./data:/data
  postgres:
    image: library/postgres:13.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  elasticsearch:
    image: library/elasticsearch:7.10.1
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./data/esdata:/usr/share/elasticsearch/data
