labels = [
  ('animal', 'fish', 'tench'),
  ('animal', 'fish', 'goldfish'),
  ('animal', 'fish', 'shark', 'great white shark', 'great white'),
  ('animal', 'fish', 'shark', 'tiger shark'),
  ('animal', 'fish', 'shark', 'hammerhead shark'),
  ('animal', 'fish', 'ray', 'electric ray'),
  ('animal', 'fish', 'ray', 'stingray'),
  ('animal', 'bird', 'chicken', 'rooster'),
  ('animal', 'bird', 'chicken', 'hen'),
  ('animal', 'bird', 'ostrich'),
  ('animal', 'bird', 'brambling'),
  ('animal', 'bird', 'goldfinch'),
  ('animal', 'bird', 'house finch'),
  ('animal', 'bird', 'junco'),
  ('animal', 'bird', 'indigo bunting'),
  ('animal', 'bird', 'robin'),
  ('animal', 'bird', 'bulbul'),
  ('animal', 'bird', 'jay'),
  ('animal', 'bird', 'magpie'),
  ('animal', 'bird', 'chickadee'),
  ('animal', 'bird', 'dipper'),
  ('animal', 'bird', 'kite'),
  ('animal', 'bird', 'bald eagle'),
  ('animal', 'bird', 'vulture'),
  ('animal', 'bird', 'owl', 'grey owl', 'great grey owl'),
  ('animal', 'amphibian', 'salamander', 'fire salamander'),
  ('animal', 'amphibian', 'smooth newt'),
  ('animal', 'amphibian', 'salamander', 'newt'),
  ('animal', 'amphibian', 'salamander', 'spotted salamander'),
  ('animal', 'amphibian', 'salamander', 'axolotl'),
  ('animal', 'amphibian', 'frog', 'bullfrog'),
  ('animal', 'amphibian', 'frog', 'tree frog'),
  ('animal', 'amphibian', 'frog', 'tailed frog'),
  ('animal', 'reptile', 'turtle', 'loggerhead sea turtle'),
  ('animal', 'reptile', 'turtle', 'sea turtle', 'leatherback sea turtle'),
  ('animal', 'reptile', 'turtle', 'mud turtle'),
  ('animal', 'reptile', 'turtle', 'terrapin'),
  ('animal', 'reptile', 'turtle', 'box turtle'),
  ('animal', 'reptile', 'lizard', 'banded gecko'),
  ('animal', 'reptile', 'lizard', 'iguana', 'green iguana'),
  ('animal', 'reptile', 'lizard', 'iguana', 'anole'),
  ('animal', 'reptile', 'lizard', 'desert grassland whiptail lizard'),
  ('animal', 'reptile', 'lizard', 'agama'),
  ('animal', 'reptile', 'lizard', 'frilled-necked lizard'),
  ('animal', 'reptile', 'lizard', 'alligator lizard'),
  ('animal', 'reptile', 'lizard', 'Gila', 'Gila monster'),
  ('animal', 'reptile', 'lizard', 'green lizard'),
  ('animal', 'reptile', 'lizard', 'chameleon'),
  ('animal', 'reptile', 'lizard', 'Komodo', 'Komodo dragon'),
  ('animal', 'reptile', 'lizard', 'crocodile'),
  ('animal', 'reptile', 'lizard', 'alligator'),
  ('animal', 'reptile', 'dinosaur', 'triceratops'),
  ('animal', 'reptile', 'snake', 'worm snake'),
  ('animal', 'reptile', 'snake', 'ring-necked snake'),
  ('animal', 'reptile', 'snake', 'eastern hog-nosed snake'),
  ('animal', 'reptile', 'snake', 'smooth green snake'),
  ('animal', 'reptile', 'snake', 'kingsnake'),
  ('animal', 'reptile', 'snake', 'garter snake'),
  ('animal', 'reptile', 'snake', 'water snake'),
  ('animal', 'reptile', 'snake', 'vine snake'),
  ('animal', 'reptile', 'snake', 'night snake'),
  ('animal', 'reptile', 'snake', 'boa constrictor'),
  ('animal', 'reptile', 'snake', 'rock python'),
  ('animal', 'reptile', 'snake', 'cobra'),
  ('animal', 'reptile', 'snake', 'green mamba'),
  ('animal', 'reptile', 'snake', 'sea snake'),
  ('animal', 'reptile', 'snake', 'viper', 'horned viper'),
  ('animal', 'reptile', 'snake', 'rattlesnake', 'eastern diamondback rattlesnake'),
  ('animal', 'reptile', 'snake', 'rattlesnake', 'sidewinder'),
  ('animal', 'insect', 'trilobite'),
  ('animal', 'insect', 'spider', 'harvestman', 'daddy long legs'),
  ('animal', 'insect', 'scorpion'),
  ('animal', 'insect', 'spider', 'yellow garden spider'),
  ('animal', 'insect', 'spider', 'barn spider'),
  ('animal', 'insect', 'spider', 'garden spider'),
  ('animal', 'insect', 'spider', 'black widow'),
  ('animal', 'insect', 'spider', 'tarantula'),
  ('animal', 'insect', 'spider', 'wolf spider'),
  ('animal', 'insect', 'tick', 'parasite'),
  ('animal', 'insect', 'centipede'),
  ('animal', 'bird', 'grouse', 'black grouse'),
  ('animal', 'bird', 'ptarmigan'),
  ('animal', 'bird', 'grouse', 'ruffed grouse'),
  ('animal', 'bird', 'grouse', 'prairie grouse'),
  ('animal', 'bird', 'peacock'),
  ('animal', 'bird', 'quail'),
  ('animal', 'bird', 'partridge'),
  ('animal', 'bird', 'parrot', 'grey parrot'),
  ('animal', 'bird', 'parrot', 'macaw'),
  ('animal', 'bird', 'parrot', 'sulphur-crested cockatoo'),
  ('animal', 'bird', 'parrot', 'lorikeet'),
  ('animal', 'bird', 'cuckoo', 'coucal'),
  ('animal', 'bird', 'bee eater'),
  ('animal', 'bird', 'hornbill'),
  ('animal', 'bird', 'hummingbird'),
  ('animal', 'bird', 'jacamar'),
  ('animal', 'bird', 'toucan'),
  ('animal', 'bird', 'duck'),
  ('animal', 'bird', 'duck', 'merganser', 'red-breasted merganser'),
  ('animal', 'bird', 'goose'),
  ('animal', 'bird', 'swan', 'black swan'),
  ('animal', 'mammal', 'tusker'),
  ('animal', 'mammal', 'marsupial', 'echidna'),
  ('animal', 'mammal', 'platypus'),
  ('animal', 'mammal', 'marsupial', 'wallaby'),
  ('animal', 'mammal', 'marsupial', 'koala'),
  ('animal', 'mammal', 'marsupial', 'wombat'),
  ('animal', 'fish', 'jellyfish'),
  ('animal', 'fish', 'coral', 'sea anemone'),
  ('animal', 'fish', 'coral', 'brain coral'),
  ('animal', 'insect', 'flatworm'),
  ('animal', 'insect', 'nematode'),
  ('animal', 'mollusk', 'conch'),
  ('animal', 'mollusk', 'snail'),
  ('animal', 'mollusk', 'slug'),
  ('animal', 'mollusk', 'slug', 'sea slug'),
  ('animal', 'mollusk', 'chiton'),
  ('animal', 'fish', 'chambered nautilus'),
  ('animal', 'mollusk', 'crab', 'Dungeness crab'),
  ('animal', 'mollusk', 'crab', 'rock crab'),
  ('animal', 'mollusk', 'crab', 'fiddler crab'),
  ('animal', 'mollusk', 'crab', 'red king crab'),
  ('animal', 'mollusk', 'lobster'),
  ('animal', 'mollusk', 'lobster', 'spiny lobster'),
  ('animal', 'mollusk', 'lobster', 'crayfish'),
  ('animal', 'mollusk', 'crab', 'hermit crab'),
  ('animal', 'mollusk', 'isopod'),
  ('animal', 'bird', 'stork', 'white stork'),
  ('animal', 'bird', 'stork', 'black stork'),
  ('animal', 'bird', 'spoonbill'),
  ('animal', 'bird', 'flamingo'),
  ('animal', 'bird', 'heron', 'little blue heron'),
  ('animal', 'bird', 'egret', 'great egret'),
  ('animal', 'bird', 'bittern'),
  ('animal', 'bird', 'crane'),
  ('animal', 'bird', 'limpkin'),
  ('animal', 'bird', 'gallinule', 'common gallinule'),
  ('animal', 'bird', 'coot'),
  ('animal', 'bird', 'bustard'),
  ('animal', 'bird', 'ruddy turnstone'),
  ('animal', 'bird', 'dunlin'),
  ('animal', 'bird', 'redshank', 'common redshank'),
  ('animal', 'bird', 'dowitcher'),
  ('animal', 'bird', 'oystercatcher'),
  ('animal', 'bird', 'pelican'),
  ('animal', 'bird', 'penguin', 'king penguin'),
  ('animal', 'bird', 'albatross'),
  ('animal', 'mammal', 'whale', 'grey whale'),
  ('animal', 'mammal', 'whale', 'killer whale'),
  ('animal', 'mammal', 'dugong'),
  ('animal', 'mammal', 'sea lion'),
  ('animal', 'mammal', 'dog', 'Chihuahua'),
  ('animal', 'mammal', 'dog', 'Japanese Chin'),
  ('animal', 'mammal', 'dog', 'Maltese'),
  ('animal', 'mammal', 'dog', 'Pekingese'),
  ('animal', 'mammal', 'dog', 'Shih Tzu'),
  ('animal', 'mammal', 'dog', 'King Charles Spaniel'),
  ('animal', 'mammal', 'dog', 'Papillon'),
  ('animal', 'mammal', 'dog', 'toy terrier'),
  ('animal', 'mammal', 'dog', 'Rhodesian Ridgeback'),
  ('animal', 'mammal', 'dog', 'Afghan Hound'),
  ('animal', 'mammal', 'dog', 'Basset Hound'),
  ('animal', 'mammal', 'dog', 'Beagle'),
  ('animal', 'mammal', 'dog', 'Bloodhound'),
  ('animal', 'mammal', 'dog', 'Bluetick Coonhound'),
  ('animal', 'mammal', 'dog', 'Black and Tan Coonhound'),
  ('animal', 'mammal', 'dog', 'Treeing Walker Coonhound'),
  ('animal', 'mammal', 'dog', 'English foxhound'),
  ('animal', 'mammal', 'dog', 'Redbone Coonhound'),
  ('animal', 'mammal', 'dog', 'borzoi'),
  ('animal', 'mammal', 'dog', 'Irish Wolfhound'),
  ('animal', 'mammal', 'dog', 'Italian Greyhound'),
  ('animal', 'mammal', 'dog', 'Whippet'),
  ('animal', 'mammal', 'dog', 'Ibizan Hound'),
  ('animal', 'mammal', 'dog', 'Norwegian Elkhound'),
  ('animal', 'mammal', 'dog', 'Otterhound'),
  ('animal', 'mammal', 'dog', 'Saluki'),
  ('animal', 'mammal', 'dog', 'Scottish Deerhound'),
  ('animal', 'mammal', 'dog', 'Weimaraner'),
  ('animal', 'mammal', 'dog', 'Staffordshire Bull Terrier'),
  ('animal', 'mammal', 'dog', 'American Staffordshire Terrier'),
  ('animal', 'mammal', 'dog', 'Bedlington Terrier'),
  ('animal', 'mammal', 'dog', 'Border Terrier'),
  ('animal', 'mammal', 'dog', 'Kerry Blue Terrier'),
  ('animal', 'mammal', 'dog', 'Irish Terrier'),
  ('animal', 'mammal', 'dog', 'Norfolk Terrier'),
  ('animal', 'mammal', 'dog', 'Norwich Terrier'),
  ('animal', 'mammal', 'dog', 'Yorkshire Terrier'),
  ('animal', 'mammal', 'dog', 'Wire Fox Terrier'),
  ('animal', 'mammal', 'dog', 'Lakeland Terrier'),
  ('animal', 'mammal', 'dog', 'Sealyham Terrier'),
  ('animal', 'mammal', 'dog', 'Airedale Terrier'),
  ('animal', 'mammal', 'dog', 'Cairn Terrier'),
  ('animal', 'mammal', 'dog', 'Australian Terrier'),
  ('animal', 'mammal', 'dog', 'Dandie Dinmont Terrier'),
  ('animal', 'mammal', 'dog', 'Boston Terrier'),
  ('animal', 'mammal', 'dog', 'Miniature Schnauzer'),
  ('animal', 'mammal', 'dog', 'Giant Schnauzer'),
  ('animal', 'mammal', 'dog', 'Standard Schnauzer'),
  ('animal', 'mammal', 'dog', 'Scottish Terrier'),
  ('animal', 'mammal', 'dog', 'Tibetan Terrier'),
  ('animal', 'mammal', 'dog', 'Australian Silky Terrier'),
  ('animal', 'mammal', 'dog', 'Soft-coated Wheaten Terrier'),
  ('animal', 'mammal', 'dog', 'West Highland White Terrier'),
  ('animal', 'mammal', 'dog', 'Lhasa Apso'),
  ('animal', 'mammal', 'dog', 'Flat-Coated Retriever'),
  ('animal', 'mammal', 'dog', 'Curly-coated Retriever'),
  ('animal', 'mammal', 'dog', 'Golden Retriever'),
  ('animal', 'mammal', 'dog', 'Labrador Retriever'),
  ('animal', 'mammal', 'dog', 'Chesapeake Bay Retriever'),
  ('animal', 'mammal', 'dog', 'German Shorthaired Pointer'),
  ('animal', 'mammal', 'dog', 'Vizsla'),
  ('animal', 'mammal', 'dog', 'English Setter'),
  ('animal', 'mammal', 'dog', 'Irish Setter'),
  ('animal', 'mammal', 'dog', 'Gordon Setter'),
  ('animal', 'mammal', 'dog', 'Brittany'),
  ('animal', 'mammal', 'dog', 'Clumber Spaniel'),
  ('animal', 'mammal', 'dog', 'English Springer Spaniel'),
  ('animal', 'mammal', 'dog', 'Welsh Springer Spaniel'),
  ('animal', 'mammal', 'dog', 'Cocker Spaniels'),
  ('animal', 'mammal', 'dog', 'Sussex Spaniel'),
  ('animal', 'mammal', 'dog', 'Irish Water Spaniel'),
  ('animal', 'mammal', 'dog', 'Kuvasz'),
  ('animal', 'mammal', 'dog', 'Schipperke'),
  ('animal', 'mammal', 'dog', 'Groenendael'),
  ('animal', 'mammal', 'dog', 'Malinois'),
  ('animal', 'mammal', 'dog', 'Briard'),
  ('animal', 'mammal', 'dog', 'Australian Kelpie'),
  ('animal', 'mammal', 'dog', 'Komondor'),
  ('animal', 'mammal', 'dog', 'Old English Sheepdog'),
  ('animal', 'mammal', 'dog', 'Shetland Sheepdog'),
  ('animal', 'mammal', 'dog', 'collie'),
  ('animal', 'mammal', 'dog', 'collie', 'Border Collie'),
  ('animal', 'mammal', 'dog', 'Bouvier des Flandres'),
  ('animal', 'mammal', 'dog', 'Rottweiler'),
  ('animal', 'mammal', 'dog', 'German Shepherd Dog'),
  ('animal', 'mammal', 'dog', 'Dobermann'),
  ('animal', 'mammal', 'dog', 'Miniature Pinscher'),
  ('animal', 'mammal', 'dog', 'Greater Swiss Mountain Dog'),
  ('animal', 'mammal', 'dog', 'Bernese Mountain Dog'),
  ('animal', 'mammal', 'dog', 'Appenzeller Sennenhund'),
  ('animal', 'mammal', 'dog', 'Entlebucher Sennenhund'),
  ('animal', 'mammal', 'dog', 'Boxer'),
  ('animal', 'mammal', 'dog', 'Bullmastiff'),
  ('animal', 'mammal', 'dog', 'Tibetan Mastiff'),
  ('animal', 'mammal', 'dog', 'French Bulldog'),
  ('animal', 'mammal', 'dog', 'Great Dane'),
  ('animal', 'mammal', 'dog', 'Saint Bernard'),
  ('animal', 'mammal', 'dog', 'husky'),
  ('animal', 'mammal', 'dog', 'husky', 'Alaskan Malamute'),
  ('animal', 'mammal', 'dog', 'husky', 'Siberian Husky'),
  ('animal', 'mammal', 'dog', 'Dalmatian'),
  ('animal', 'mammal', 'dog', 'Affenpinscher'),
  ('animal', 'mammal', 'dog', 'Basenji'),
  ('animal', 'mammal', 'dog', 'pug'),
  ('animal', 'mammal', 'dog', 'Leonberger'),
  ('animal', 'mammal', 'dog', 'Newfoundland'),
  ('animal', 'mammal', 'dog', 'Pyrenean Mountain Dog'),
  ('animal', 'mammal', 'dog', 'Samoyed'),
  ('animal', 'mammal', 'dog', 'Pomeranian'),
  ('animal', 'mammal', 'dog', 'Chow Chow'),
  ('animal', 'mammal', 'dog', 'Keeshond'),
  ('animal', 'mammal', 'dog', 'Griffon Bruxellois'),
  ('animal', 'mammal', 'dog', 'corgi', 'Pembroke Welsh Corgi'),
  ('animal', 'mammal', 'dog', 'corgi', 'Cardigan Welsh Corgi'),
  ('animal', 'mammal', 'dog', 'poodle', 'Toy Poodle'),
  ('animal', 'mammal', 'dog', 'poodle', 'Miniature Poodle'),
  ('animal', 'mammal', 'dog', 'poodle', 'Standard Poodle'),
  ('animal', 'mammal', 'dog', 'Mexican hairless dog'),
  ('animal', 'mammal', 'wolf', 'grey wolf'),
  ('animal', 'mammal', 'wolf', 'Alaskan tundra wolf'),
  ('animal', 'mammal', 'wolf', 'red wolf'),
  ('animal', 'mammal', 'coyote'),
  ('animal', 'mammal', 'dingo'),
  ('animal', 'mammal', 'dhole'),
  ('animal', 'mammal', 'dog', 'African wild dog'),
  ('animal', 'mammal', 'hyena'),
  ('animal', 'mammal', 'fox', 'red fox'),
  ('animal', 'mammal', 'fox', 'kit fox'),
  ('animal', 'mammal', 'fox', 'Arctic fox'),
  ('animal', 'mammal', 'fox', 'grey fox'),
  ('animal', 'mammal', 'cat', 'tabby cat'),
  ('animal', 'mammal', 'cat', 'tiger cat'),
  ('animal', 'mammal', 'cat', 'Persian cat'),
  ('animal', 'mammal', 'cat', 'Siamese cat'),
  ('animal', 'mammal', 'cat', 'Egyptian Mau'),
  ('animal', 'mammal', 'cougar'),
  ('animal', 'mammal', 'lynx'),
  ('animal', 'mammal', 'leopard'),
  ('animal', 'mammal', 'leopard', 'snow leopard'),
  ('animal', 'mammal', 'jaguar'),
  ('animal', 'mammal', 'lion'),
  ('animal', 'mammal', 'tiger'),
  ('animal', 'mammal', 'cheetah'),
  ('animal', 'mammal', 'bear', 'brown bear'),
  ('animal', 'mammal', 'bear', 'black bear'),
  ('animal', 'mammal', 'bear', 'polar bear'),
  ('animal', 'mammal', 'bear', 'sloth bear'),
  ('animal', 'mammal', 'mongoose'),
  ('animal', 'mammal', 'meerkat'),
  ('animal', 'insect', 'beetle', 'tiger beetle'),
  ('animal', 'insect', 'beetle', 'ladybug'),
  ('animal', 'insect', 'beetle', 'ground beetle'),
  ('animal', 'insect', 'beetle', 'longhorn beetle'),
  ('animal', 'insect', 'beetle', 'leaf beetle'),
  ('animal', 'insect', 'beetle', 'dung beetle'),
  ('animal', 'insect', 'beetle', 'rhinoceros beetle'),
  ('animal', 'insect', 'beetle', 'weevil'),
  ('animal', 'insect', 'fly'),
  ('animal', 'insect', 'bee'),
  ('animal', 'insect', 'ant'),
  ('animal', 'insect', 'grasshopper'),
  ('animal', 'insect', 'cricket'),
  ('animal', 'insect', 'stick insect'),
  ('animal', 'insect', 'cockroach'),
  ('animal', 'insect', 'mantis'),
  ('animal', 'insect', 'cicada'),
  ('animal', 'insect', 'leafhopper'),
  ('animal', 'insect', 'lacewing'),
  ('animal', 'insect', 'dragonfly'),
  ('animal', 'insect', 'damselfly'),
  ('animal', 'insect', 'red admiral'),
  ('animal', 'insect', 'ringlet'),
  ('animal', 'insect', 'butterfly', 'monarch butterfly'),
  ('animal', 'insect', 'butterfly', 'small white'),
  ('animal', 'insect', 'butterfly', 'sulphur butterfly'),
  ('animal', 'insect', 'butterfly', 'gossamer-winged butterfly'),
  ('animal', 'fish', 'coral', 'starfish'),
  ('animal', 'fish', 'coral', 'sea urchin'),
  ('animal', 'fish', 'coral', 'sea cucumber'),
  ('animal', 'mammal', 'rabbit', 'cottontail rabbit'),
  ('animal', 'mammal', 'rabbit', 'hare'),
  ('animal', 'mammal', 'rabbit', 'Angora rabbit'),
  ('animal', 'mammal', 'hamster'),
  ('animal', 'mammal', 'porcupine'),
  ('animal', 'mammal', 'squirrel', 'fox squirrel'),
  ('animal', 'mammal', 'marmot'),
  ('animal', 'mammal', 'beaver'),
  ('animal', 'mammal', 'guinea pig'),
  ('animal', 'mammal', 'common sorrel'),
  ('animal', 'mammal', 'zebra'),
  ('animal', 'mammal', 'pig'),
  ('animal', 'mammal', 'wild boar'),
  ('animal', 'mammal', 'warthog'),
  ('animal', 'mammal', 'hippopotamus'),
  ('animal', 'mammal', 'ox'),
  ('animal', 'mammal', 'water buffalo'),
  ('animal', 'mammal', 'bison'),
  ('animal', 'mammal', 'sheep', 'ram'),
  ('animal', 'mammal', 'sheep', 'bighorn sheep'),
  ('animal', 'mammal', 'ibex', 'Alpine ibex'),
  ('animal', 'mammal', 'hartebeest'),
  ('animal', 'mammal', 'impala'),
  ('animal', 'mammal', 'gazelle'),
  ('animal', 'mammal', 'camel', 'dromedary'),
  ('animal', 'mammal', 'llama'),
  ('animal', 'mammal', 'ferret', 'weasel'),
  ('animal', 'mammal', 'ferret', 'mink'),
  ('animal', 'mammal', 'ferret', 'polecat', 'European polecat'),
  ('animal', 'mammal', 'ferret', 'black-footed ferret'),
  ('animal', 'mammal', 'otter'),
  ('animal', 'mammal', 'skunk'),
  ('animal', 'mammal', 'badger'),
  ('animal', 'mammal', 'armadillo'),
  ('animal', 'mammal', 'sloth', 'three-toed sloth'),
  ('animal', 'mammal', 'ape', 'orangutan'),
  ('animal', 'mammal', 'ape', 'gorilla'),
  ('animal', 'mammal', 'ape', 'chimpanzee'),
  ('animal', 'mammal', 'ape', 'gibbon'),
  ('animal', 'mammal', 'ape', 'gibbon', 'siamang'),
  ('animal', 'mammal', 'monkey', 'guenon'),
  ('animal', 'mammal', 'monkey', 'patas monkey'),
  ('animal', 'mammal', 'monkey', 'baboon'),
  ('animal', 'mammal', 'monkey', 'macaque'),
  ('animal', 'mammal', 'monkey', 'langur'),
  ('animal', 'mammal', 'monkey', 'black-and-white colobus'),
  ('animal', 'mammal', 'monkey', 'proboscis monkey'),
  ('animal', 'mammal', 'monkey', 'marmoset'),
  ('animal', 'mammal', 'monkey', 'white-headed capuchin'),
  ('animal', 'mammal', 'monkey', 'howler monkey'),
  ('animal', 'mammal', 'monkey', 'titi'),
  ('animal', 'mammal', 'monkey', 'spider monkey'),
  ('animal', 'mammal', 'monkey', 'squirrel monkey', 'common squirrel monkey'),
  ('animal', 'mammal', 'lemur', 'ring-tailed lemur'),
  ('animal', 'mammal', 'lemur', 'indri'),
  ('animal', 'mammal', 'elephant', 'Asian elephant'),
  ('animal', 'mammal', 'elephant', 'African bush elephant'),
  ('animal', 'mammal', 'panda', 'red panda'),
  ('animal', 'mammal', 'panda', 'giant panda'),
  ('animal', 'fish', 'snoek'),
  ('animal', 'fish', 'eel'),
  ('animal', 'fish', 'coho salmon'),
  ('animal', 'fish', 'rock beauty'),
  ('animal', 'fish', 'clownfish'),
  ('animal', 'fish', 'sturgeon'),
  ('animal', 'fish', 'garfish'),
  ('animal', 'fish', 'lionfish'),
  ('animal', 'fish', 'pufferfish'),
  ('object', 'tool', 'abacus'),
  ('object', 'clothing', 'abaya'),
  ('object', 'clothing', 'academic gown'),
  ('object', 'instrument', 'accordion'),
  ('object', 'instrument', 'guitar', 'acoustic guitar'),
  ('object', 'vehicle', 'boat', 'aircraft carrier'),
  ('object', 'vehicle', 'plane', 'airliner'),
  ('object', 'vehicle', 'blimp', 'airship'),
  ('object', 'altar'),
  ('object', 'vehicle', 'ambulance'),
  ('object', 'vehicle', 'amphibious vehicle'),
  ('object', 'clock', 'analog clock'),
  ('object', 'apiary'),
  ('object', 'clothing', 'apron'),
  ('object', 'container', 'waste container'),
  ('object', 'weapon', 'assault rifle'),
  ('object', 'container', 'bag', 'backpack'),
  ('structure', 'building', 'bakery'),
  ('object', 'balance beam'),
  ('object', 'balloon'),
  ('object', 'stationary', 'ballpoint pen'),
  ('object', 'medical', 'Band-Aid'),
  ('object', 'instrument', 'banjo'),
  ('object', 'baluster'),
  ('object', 'barbell'),
  ('furniture', 'chair', 'barber chair'),
  ('structure', 'building', 'barbershop'),
  ('structure', 'building', 'barn'),
  ('object', 'tool', 'barometer'),
  ('object', 'container', 'barrel'),
  ('object', 'tool', 'wheelbarrow'),
  ('object', 'ball', 'baseball'),
  ('object', 'ball', 'basketball'),
  ('object', 'instrument', 'bassinet'),
  ('object', 'instrument', 'bassoon'),
  ('object', 'clothing', 'cap', 'swimming cap'),
  ('object', 'bath towel'),
  ('object', 'bathtub'),
  ('object', 'vehicle', 'car', 'station wagon'),
  ('object', 'building', 'lighthouse'),
  ('object', 'container', 'beaker'),
  ('object', 'clothing', 'cap', 'military cap'),
  ('object', 'container', 'bottle', 'beer bottle'),
  ('object', 'container', 'glass', 'beer glass'),
  ('furniture', 'bed', 'bell-cot'),
  ('object', 'clothing', 'bib'),
  ('vehicle', 'bike', 'bicycle', 'tandem bicycle'),
  ('object', 'clothing', 'bikini'),
  ('object', 'stationary', 'ring binder'),
  ('object', 'tool', 'binoculars'),
  ('structure', 'building', 'birdhouse'),
  ('structure', 'building', 'boathouse'),
  ('vehicle', 'sled', 'bobsled'),
  ('object', 'clothing', 'bolo tie'),
  ('object', 'clothing', 'poke bonnet'),
  ('furniture', 'shelf', 'bookcase'),
  ('structure', 'building', 'bookstore'),
  ('object', 'bottle cap'),
  ('object', 'weapon', 'bow'),
  ('object', 'clothing', 'bow tie'),
  ('structure', 'memorial', 'brass'),
  ('object', 'clothing', 'bra'),
  ('structure', 'breakwater'),
  ('object', 'armor', 'breastplate'),
  ('object', 'tool', 'broom'),
  ('object', 'container', 'bucket'),
  ('object', 'clothing', 'buckle'),
  ('object', 'clothing', 'armor', 'vest', 'bulletproof vest'),
  ('vehicle', 'train', 'high-speed train'),
  ('structure', 'building', 'butcher shop'),
  ('vehicle', 'car', 'taxi', 'taxicab'),
  ('object', 'container', 'cauldron'),
  ('object', 'candle'),
  ('object', 'weapon', 'cannon'),
  ('object', 'vehicle', 'boat', 'canoe'),
  ('object', 'utensil', 'can opener'),
  ('object', 'clothing', 'cardigan'),
  ('object', 'car mirror'),
  ('structure', 'carousel'),
  ('object', 'tool', 'tool kit'),
  ('object', 'container', 'carton'),
  ('object', 'car wheel'),
  ('object', 'machine', 'automated teller machine', 'atm'),
  ('object', 'technology', 'cassette'),
  ('object', 'technology', 'cassette player'),
  ('structure', 'castle'),
  ('object', 'vehicle', 'boat', 'catamaran'),
  ('object', 'technology', 'CD player'),
  ('object', 'instrument', 'cello'),
  ('object', 'technology', 'phone', 'mobile phone'),
  ('object', 'hardware', 'chain'),
  ('structure', 'fence', 'chain-link fence'),
  ('object', 'clothing', 'armor', 'chain mail'),
  ('object', 'tool', 'chainsaw'),
  ('furniture', 'chest'),
  ('furniture', 'chiffonier'),
  ('furniture', 'decoration', 'chime'),
  ('furniture', 'china cabinet'),
  ('furniture', 'decoration', 'Christmas stocking'),
  ('structure', 'building', 'church'),
  ('structure', 'building', 'movie theater'),
  ('object', 'utensil', 'cleaver'),
  ('structure', 'cliff dwelling'),
  ('object', 'clothing', 'cape', 'cloak'),
  ('object', 'clothing', 'shoes', 'clogs'),
  ('object', 'dish', 'cocktail shaker'),
  ('object', 'dish', 'mug', 'coffee mug'),
  ('object', 'appliance', 'coffeemaker'),
  ('object', 'coil'),
  ('object', 'tool', 'lock', 'combination lock'),
  ('object', 'technology', 'keyboard', 'computer keyboard'),
  ('structure', 'building', 'confectionery store'),
  ('vehicle', 'ship', 'container ship'),
  ('vehicle', 'car', 'convertible'),
  ('object', 'utensil', 'corkscrew'),
  ('object', 'instrument', 'trumpet', 'cornet'),
  ('object', 'clothing', 'boots', 'cowboy boot'),
  ('object', 'clothing', 'hat', 'cowboy hat'),
  ('furniture', 'bed', 'cradle'),
  ('vehicle', 'crane'),
  ('object', 'clothing', 'helmet', 'crash helmet'),
  ('object', 'container', 'crate'),
  ('furniture', 'bed', 'infant bed'),
  ('object', 'appliance', 'Crock Pot'),
  ('object', 'ball', 'croquet ball'),
  ('object', 'crutch'),
  ('object', 'clothing', 'cuirass'),
  ('structure', 'dam'),
  ('furniture', 'desk'),
  ('object', 'technology', 'computer', 'desktop computer'),
  ('object', 'technology', 'phone', 'rotary dial telephone'),
  ('object', 'clothing', 'diaper'),
  ('object', 'technology', 'clock', 'digital clock'),
  ('object', 'technology', 'clock', 'digital watch'),
  ('furniture', 'table', 'dining table'),
  ('object', 'cloth', 'dishcloth'),
  ('object', 'appliance', 'dishwasher'),
  ('object', 'disc brake'),
  ('structure', 'dock'),
  ('vehicle', 'sled', 'dog sled'),
  ('structure', 'dome'),
  ('object', 'doormat'),
  ('structure', 'drilling rig'),
  ('object', 'instrument', 'drum'),
  ('object', 'instrument', 'drum', 'drumstick'),
  ('object', 'dumbbell'),
  ('object', 'appliance', 'oven', 'Dutch oven'),
  ('object', 'appliance', 'fan', 'electric fan'),
  ('object', 'instrument', 'guitar', 'electric guitar'),
  ('vehicle', 'train', 'electric locomotive'),
  ('furniture', 'entertainment center'),
  ('object', 'stationary', 'envelope'),
  ('object', 'appliance', 'espresso machine'),
  ('object', 'face powder'),
  ('object', 'clothing', 'accessory', 'feather boa'),
  ('furniture', 'filing cabinet'),
  ('vehicle', 'boat', 'fireboat'),
  ('vehicle', 'truck', 'fire engine'),
  ('object', 'fire screen sheet'),
  ('structure', 'flagpole'),
  ('object', 'instrument', 'flute'),
  ('furniture', 'chair', 'folding chair'),
  ('object', 'clothing', 'helmet', 'football helmet'),
  ('vehicle', 'forklift'),
  ('structure', 'fountain'),
  ('object', 'stationary', 'fountain pen'),
  ('furniture', 'bed', 'four-poster bed'),
  ('vehicle', 'train', 'freight car'),
  ('object', 'instrument', 'French horn'),
  ('object', 'cookware', 'pan', 'frying pan'),
  ('object', 'clothing', 'coat', 'fur coat'),
  ('vehicle', 'truck', 'garbage truck'),
  ('object', 'clothing', 'mask', 'gas mask'),
  ('structure', 'gas pump'),
  ('object', 'dish', 'goblet'),
  ('vehicle', 'cart', 'go-kart'),
  ('object', 'ball', 'golf ball'),
  ('vehicle', 'cart', 'golf cart'),
  ('vehicle', 'boat', 'gondola'),
  ('object', 'instrument', 'gong'),
  ('object', 'clothing', 'gown'),
  ('object', 'instrument', 'grand piano'),
  ('structure', 'building', 'greenhouse'),
  ('object', 'cookware', 'grill'),
  ('structure', 'building', 'grocery store'),
  ('structure', 'guillotine'),
  ('object', 'clothing', 'accessory', 'barrette'),
  ('object', 'hair spray'),
  ('vehicle', 'half-track'),
  ('object', 'tool', 'hammer'),
  ('furniture', 'hamper'),
  ('object', 'appliance', 'hair dryer'),
  ('object', 'technology', 'computer', 'hand-held computer'),
  ('object', 'cloth', 'handkerchief'),
  ('object', 'technology', 'hard disk drive', 'hdd'),
  ('object', 'instrument', 'harmonica'),
  ('object', 'instrument', 'harp'),
  ('vehicle', 'harvester'),
  ('object', 'tool', 'hatchet'),
  ('object', 'clothing', 'accessory', 'holster'),
  ('structure', 'building', 'home theater'),
  ('object', 'honeycomb'),
  ('object', 'tool', 'hook'),
  ('object', 'clothing', 'skirt', 'hoop skirt'),
  ('object', 'horizontal bar'),
  ('vehicle', 'horse-drawn vehicle'),
  ('object', 'hourglass'),
  ('object', 'technology', 'iPod'),
  ('object', 'appliance', 'clothes iron'),
  ('furniture', 'decoration', 'jack-o-lantern', 'pumpkin'),
  ('object', 'clothing', 'pants', 'jeans'),
  ('vehicle', 'car', 'jeep'),
  ('object', 'clothing', 'shirt', 't-shirt'),
  ('object', 'game', 'jigsaw puzzle'),
  ('vehicle', 'pulled rickshaw'),
  ('object', 'game', 'joystick'),
  ('object', 'clothing', 'kimono'),
  ('object', 'clothing', 'knee pad'),
  ('object', 'knot'),
  ('object', 'clothing', 'coat', 'lab coat'),
  ('object', 'utensil', 'ladle'),
  ('furniture', 'lampshade'),
  ('object', 'technology', 'computer', 'laptop', 'laptop computer'),
  ('object', 'machine', 'lawn mower'),
  ('object', 'lens cap'),
  ('object', 'tool', 'paper knife'),
  ('structure', 'building', 'library'),
  ('vehicle', 'boat', 'lifeboat'),
  ('object', 'tool', 'lighter'),
  ('vehicle', 'car', 'limousine'),
  ('vehicle', 'ship', 'ocean liner'),
  ('object', 'lipstick'),
  ('object', 'clothing', 'shoe', 'slip-on shoe'),
  ('object', 'lotion'),
  ('object', 'technology', 'speaker'),
  ('object', 'loupe'),
  ('structure', 'building', 'sawmill'),
  ('object', 'tool', 'magnetic compass'),
  ('object', 'container', 'bag', 'mail bag'),
  ('structure', 'mailbox'),
  ('object', 'clothing', 'pants', 'tights'),
  ('object', 'clothing', 'tank suit'),
  ('object', 'manhole cover'),
  ('object', 'instrument', 'maraca'),
  ('object', 'instrument', 'marimba'),
  ('object', 'clothing', 'mask'),
  ('object', 'match'),
  ('structure', 'maypole'),
  ('structure', 'maze'),
  ('object', 'utensil', 'measuring cup'),
  ('furniture', 'chest', 'medicine chest'),
  ('structure', 'megalith'),
  ('object', 'technology', 'microphone'),
  ('object', 'appliance', 'microwave oven'),
  ('object', 'clothing', 'military uniform'),
  ('object', 'container', 'can', 'milk can'),
  ('vehicle', 'bus', 'minibus'),
  ('object', 'clothing', 'skirt', 'miniskirt'),
  ('vehicle', 'van', 'minivan'),
  ('object', 'weapon', 'missile'),
  ('object', 'clothing', 'mitten', 'mit'),
  ('object', 'utensil', 'mixing bowl'),
  ('vehicle', 'mobile home'),
  ('vehicle', 'car', 'Model T'),
  ('object', 'technology', 'modem'),
  ('structure', 'building', 'monastery'),
  ('object', 'technology', 'monitor'),
  ('vehicle', 'scooter', 'moped'),
  ('object', 'weapon', 'mortar'),
  ('object', 'clothing', 'cap', 'mortarboard'),
  ('structure', 'building', 'mosque'),
  ('object', 'mosquito net'),
  ('vehicle', 'scooter'),
  ('vehicle', 'bike', 'mountain bike'),
  ('structure', 'tent'),
  ('object', 'technology', 'mouse', 'computer mouse'),
  ('object', 'mousetrap'),
  ('vehicle', 'van', 'moving van'),
  ('object', 'muzzle'),
  ('object', 'hardware', 'nail'),
  ('object', 'neck brace'),
  ('object', 'clothing', 'accessory', 'necklace'),
  ('object', 'nipple'),
  ('object', 'technology', 'computer', 'notebook computer'),
  ('structure', 'obelisk'),
  ('object', 'instrument', 'oboe'),
  ('object', 'instrument', 'ocarina'),
  ('object', 'odometer'),
  ('object', 'hardware', 'oil filter'),
  ('object', 'instrument', 'organ'),
  ('object', 'technology', 'oscilloscope'),
  ('object', 'clothing', 'skirt', 'overskirt'),
  ('vehicle', 'cart', 'bullock cart'),
  ('object', 'clothing', 'mask', 'oxygen mask'),
  ('object', 'packet'),
  ('object', 'paddle'),
  ('vehicle', 'boat', 'paddle wheel'),
  ('object', 'lock', 'padlock'),
  ('object', 'stationary', 'paintbrush'),
  ('object', 'clothing', 'pajamas'),
  ('structure', 'building', 'palace'),
  ('object', 'instrument', 'flute', 'pan flute'),
  ('object', 'paper towel'),
  ('object', 'parachute'),
  ('object', 'parallel bars'),
  ('structure', 'park bench'),
  ('structure', 'parking meter'),
  ('vehicle', 'train', 'passenger car'),
  ('structure', 'patio'),
  ('structure', 'payphone'),
  ('structure', 'pedestal'),
  ('object', 'stationary', 'pencil case'),
  ('object', 'stationary', 'pencil sharpener'),
  ('object', 'perfume'),
  ('object', 'dish', 'Petri dish'),
  ('object', 'machine', 'photocopier'),
  ('object', 'plectrum'),
  ('object', 'clothing', 'helmet', 'pickelhaube'),
  ('structure', 'fence', 'picket fence'),
  ('vehicle', 'truck', 'pickup truck'),
  ('structure', 'pier'),
  ('object', 'container', 'piggy bank'),
  ('object', 'container', 'bottle', 'pill bottle'),
  ('object', 'pillow'),
  ('object', 'ball', 'ping-pong ball'),
  ('object', 'pinwheel'),
  ('vehicle', 'ship', 'pirate ship'),
  ('object', 'container', 'pitcher'),
  ('vehicle', 'plane', 'hand plane'),
  ('structure', 'building', 'theatre', 'planetarium'),
  ('object', 'container', 'bag', 'plastic bag'),
  ('furniture', 'plate rack'),
  ('object', 'tool', 'farm', 'plow'),
  ('object', 'tool', 'plunger'),
  ('object', 'technology', 'Polaroid camera'),
  ('structure', 'pole'),
  ('vehicle', 'van', 'police van'),
  ('object', 'clothing', 'poncho'),
  ('furniture', 'table', 'billiard table'),
  ('object', 'container', 'bottle', 'soda bottle'),
  ('object', 'cookware', 'pot'),
  ('object', 'pottery wheel'),
  ('object', 'tool', 'power drill'),
  ('object', 'prayer rug'),
  ('object', 'technology', 'printer'),
  ('structure', 'building', 'prison'),
  ('object', 'weapon', 'projectile'),
  ('object', 'technology', 'projector'),
  ('object', 'ball', 'hockey puck'),
  ('object', 'decoration', 'punching bag'),
  ('object', 'clothing', 'accessory', 'purse'),
  ('object', 'stationary', 'quill'),
  ('object', 'quilt'),
  ('vehicle', 'car', 'race car'),
  ('object', 'sport', 'racket'),
  ('object', 'radiator'),
  ('object', 'technology', 'radio'),
  ('object', 'technology', 'radio telescope'),
  ('object', 'container', 'rain barrel'),
  ('object', 'vehicle', 'recreational vehicle', 'rv'),
  ('object', 'reel'),
  ('object', 'technology', 'camera', 'reflex camera'),
  ('object', 'appliance', 'refrigerator'),
  ('object', 'technology', 'remote control'),
  ('structure', 'building', 'restaurant'),
  ('object', 'weapon', 'gun', 'revolver'),
  ('object', 'weapon', 'gun', 'rifle'),
  ('furniture', 'chair', 'rocking chair'),
  ('object', 'cookware', 'rotisserie'),
  ('object', 'stationary', 'eraser'),
  ('object', 'sport', 'ball', 'rugby ball'),
  ('object', 'stationary', 'ruler'),
  ('object', 'clothing', 'shoe', 'running shoe'),
  ('object', 'safe'),
  ('object', 'safety pin'),
  ('object', 'salt shaker'),
  ('object', 'clothing', 'shoe', 'sandal'),
  ('object', 'clothing', 'sarong'),
  ('object', 'instrument', 'saxophone'),
  ('object', 'clothing', 'accessory', 'scabbard'),
  ('object', 'appliance', 'weighing scale'),
  ('vehicle', 'bus', 'school bus'),
  ('object', 'vehicle', 'boat', 'schooner'),
  ('structure', 'scoreboard'),
  ('object', 'technology', 'screen', 'crt screen'),
  ('object', 'hardware', 'screw'),
  ('object', 'tool', 'screwdriver'),
  ('object', 'seat belt'),
  ('object', 'machine', 'sewing machine'),
  ('object', 'clothing', 'armor', 'shield'),
  ('structure', 'building', 'shoe store'),
  ('structure', 'shoji'),
  ('object', 'shopping basket'),
  ('object', 'shopping cart'),
  ('object', 'tool', 'shovel'),
  ('object', 'clothing', 'cap', 'shower cap'),
  ('object', 'shower curtain'),
  ('object', 'sport', 'ski'),
  ('object', 'ski mask'),
  ('object', 'sleeping bag'),
  ('object', 'stationary', 'slide rule'),
  ('structure', 'sliding door'),
  ('object', 'machine', 'slot machine'),
  'snorkel',
  ('object', 'vehicle', 'snowmobile'),
  ('object', 'vehicle', 'snowplow'),
  ('object', 'soap dispenser'),
  ('object', 'sport', 'ball', 'soccer ball'),
  ('object', 'clothing', 'sock'),
  ('object', 'technology', 'solar thermal collector'),
  ('object', 'clothing', 'hat', 'sombrero'),
  ('object', 'dish', 'soup bowl'),
  ('furniture', 'space bar'),
  ('object', 'appliance', 'space heater'),
  ('object', 'vehicle', 'rocket', 'space shuttle'),
  ('object', 'utensil', 'spatula'),
  ('object', 'vehicle', 'boat', 'motorboat'),
  ('object', 'spider web'),
  ('object', 'spindle'),
  ('object', 'vehicle', 'car', 'sports car'),
  ('object', 'appliance', 'spotlight'),
  ('structure', 'theatre', 'stage'),
  ('vehicle', 'train', 'steam locomotive'),
  ('structure', 'bridge', 'arch bridge'),
  ('object', 'instrument', 'drum', 'steel drum'),
  ('object', 'tool', 'medical', 'stethoscope'),
  ('object', 'clothing', 'accessory', 'scarf'),
  ('structure', 'wall', 'stone wall'),
  ('object', 'technology', 'stopwatch'),
  ('object', 'appliance', 'stove'),
  ('object', 'cookware', 'strainer'),
  ('vehicle', 'train', 'tram'),
  ('furniture', 'stretcher'),
  ('furniture', 'couch'),
  ('structure', 'building', 'stupa'),
  ('object', 'vehicle', 'submarine'),
  ('object', 'clothing', 'suit'),
  ('structure', 'sundial'),
  ('object', 'clothing', 'accessory', 'sunglass'),
  ('object', 'clothing', 'accessory', 'sunglasses'),
  ('object', 'sunscreen'),
  ('structure', 'bridge', 'suspension bridge'),
  ('object', 'tool', 'mop'),
  ('object', 'clothing', 'sweatshirt'),
  ('object', 'clothing', 'swimsuit'),
  ('structure', 'swing'),
  ('object', 'switch'),
  ('object', 'tool', 'medical', 'syringe'),
  ('furniture', 'lamp', 'table lamp'),
  ('vehicle', 'tank'),
  ('object', 'technology', 'tape player'),
  ('object', 'container', 'teapot'),
  ('object', 'teddy bear'),
  ('object', 'technology', 'television'),
  ('object', 'sport', 'ball', 'tennis ball'),
  ('structure', 'thatched roof'),
  ('object', 'front curtain'),
  ('object', 'thimble'),
  ('object', 'machine', 'threshing machine'),
  ('furniture', 'chair', 'throne'),
  ('structure', 'tile roof'),
  ('object', 'appliance', 'toaster'),
  ('structure', 'building', 'tobacco shop'),
  ('object', 'toilet seat'),
  ('object', 'torch'),
  ('structure', 'totem pole'),
  ('vehicle', 'trucl', 'tow truck'),
  ('structure', 'building', 'toy store'),
  ('vehicle', 'tractor'),
  ('vehicle', 'truck', 'semi-trailer truck'),
  ('object', 'tray'),
  ('object', 'clothing', 'trench coat'),
  ('vehicle', 'tricycle'),
  ('vehicle', 'boat', 'trimaran'),
  ('object', 'tripod'),
  ('structure', 'monument', 'triumphal arch'),
  ('vehicle', 'bus', 'trolleybus', 'trolley'),
  ('object', 'instrument', 'trombone'),
  ('object', 'tub'),
  ('structure', 'gate', 'turnstile'),
  ('object', 'technology', 'typewriter keyboard'),
  ('object', 'umbrella'),
  ('vehicle', 'unicycle'),
  ('object', 'instrument', 'piano', 'upright piano'),
  ('object', 'appliance', 'vacuum cleaner'),
  ('object', 'container', 'vase'),
  ('structure', 'vault'),
  ('object', 'velvet'),
  ('object', 'machine', 'vending machine'),
  ('object', 'clothing', 'vestment'),
  ('structure', 'viaduct'),
  ('object', 'instrument', 'violin'),
  ('object', 'sport', 'ball', 'volleyball'),
  ('object', 'appliance', 'waffle iron'),
  ('object', 'technology', 'wall clock'),
  ('object', 'wallet'),
  ('furniture', 'wardrobe'),
  ('vehicle', 'military aircraft'),
  ('object', 'sink'),
  ('object', 'appliance', 'washing machine'),
  ('object', 'container', 'bottle', 'water bottle'),
  ('object', 'container', 'jug', 'water jug'),
  ('structure', 'water tower'),
  ('object', 'container', 'jug', 'whiskey jug'),
  ('object', 'tool', 'whistle'),
  ('object', 'clothing', 'accessory', 'wig'),
  ('object', 'window screen'),
  ('object', 'window shade'),
  ('object', 'clothing', 'tie', 'Windsor tie'),
  ('object', 'container', 'bottle', 'wine bottle'),
  ('object', 'wing'),
  ('object', 'cookware', 'wok'),
  ('object', 'utensil', 'wooden spoon'),
  ('object', 'wool'),
  ('structure', 'fence', 'split-rail fence'),
  ('structure', 'shipwreck'),
  ('vehicle', 'boat', 'yawl'),
  ('structure', 'yurt'),
  ('object', 'website'),
  ('object', 'comic book'),
  ('object', 'crossword'),
  ('object', 'traffic sign'),
  ('object', 'traffic light'),
  ('object', 'jacket', 'dust jacket'),
  ('object', 'menu'),
  ('object', 'dish', 'plate'),
  ('food', 'dip', 'guacamole'),
  ('food', 'soup', 'consomme'),
  ('food', 'soup', 'hot pot'),
  ('food', 'dessert', 'trifle'),
  ('food', 'dessert', 'ice cream'),
  ('food', 'dessert', 'ice pop'),
  ('food', 'bread', 'baguette'),
  ('food', 'bread', 'bagel'),
  ('food', 'bread', 'pretzel'),
  ('food', 'cheeseburger'),
  ('food', 'hot dog'),
  ('food', 'mashed potato'),
  ('food', 'vegetable', 'cabbage'),
  ('food', 'vegetable', 'broccoli'),
  ('food', 'vegetable', 'cauliflower'),
  ('food', 'vegetable', 'zucchini'),
  ('food', 'vegetable', 'squash', 'spaghetti squash'),
  ('food', 'vegetable', 'squash', 'acorn squash'),
  ('food', 'vegetable', 'squash', 'butternut squash'),
  ('food', 'vegetable', 'cucumber'),
  ('food', 'vegetable', 'artichoke'),
  ('food', 'vegetable', 'bell pepper'),
  ('plant', 'cardoon'),
  ('plant', 'fungus', 'mushroom'),
  ('food', 'fruit', 'apple', 'granny smith'),
  ('food', 'fruit', 'strawberry'),
  ('food', 'fruit', 'orange'),
  ('food', 'fruit', 'lemon'),
  ('food', 'fruit', 'fig'),
  ('food', 'fruit', 'pineapple'),
  ('food', 'fruit', 'banana'),
  ('food', 'fruit', 'jackfruit'),
  ('food', 'fruit', 'custard apple'),
  ('food', 'fruit', 'pomegranate'),
  ('plant', 'hay'),
  ('food', 'carbonara'),
  ('food', 'dessert', 'chocolate syrup'),
  ('food', 'dough'),
  ('food', 'meatloaf'),
  ('food', 'pizza'),
  ('food', 'pot pie'),
  ('food', 'burrito'),
  ('drink', 'alcohol', 'red wine'),
  ('drink', 'espresso'),
  ('object', 'dish', 'cup'),
  ('drink', 'eggnog'),
  ('landscape', 'alp'),
  ('object', 'bubble'),
  ('landscape', 'cliff'),
  ('landscape', 'coral reef'),
  ('landscape', 'geyser'),
  ('landscape', 'lakeshore'),
  ('landscape', 'promontory'),
  ('landscape', 'shoal'),
  ('landscape', 'seashore'),
  ('landscape', 'valley'),
  ('landscape', 'volcano'),
  ('person', 'baseball player'),
  ('person', 'bridegroom'),
  ('person', 'diver', 'scuba diver'),
  ('plant', 'rapeseed'),
  ('plant', 'flower', 'daisy'),
  ('plant', 'flower', 'yellow lady\'s slipper'),
  ('plant', 'food', 'corn'),
  ('plant', 'nut', 'acorn'),
  ('plant', 'rose hip', 'rosehip'),
  ('plant', 'nut', 'chestnut', 'horse chestnut seed'),
  ('plant', 'fungus', 'coral fungus'),
  ('plant', 'fungus', 'agaric'),
  ('plant', 'fungus', 'gyromitra'),
  ('plant', 'fungus', 'mushroom', 'stinkhorn mushroom'),
  ('plant', 'fungus', 'earth star'),
  ('plant', 'fungus', 'hen-of-the-woods'),
  ('plant', 'fungus', 'bolete'),
  ('plant', 'corn', 'ear', 'corn ear'),
  ('object', 'toilet paper'),
]
