"""
Custom hand-annotated labels for the COCO2017 dataset
https://cocodataset.org
"""
from model.dataset import Label, Dataset

coco_labels = [
  Label(('person', 'person')),
  Label(('vehicle', 'bicycle'), alt=('bike',)),
  Label(('vehicle', 'car')),
  Label(('vehicle', 'motorcycle')),
  Label(('vehicle', 'airplane'), alt=('plane',)),
  Label(('vehicle', 'bus')),
  Label(('vehicle', 'train')),
  Label(('vehicle', 'truck')),
  Label(('vehicle', 'boat'), alt=('ship',)),
  Label(('object', 'traffic light'), related=('street',)),
  Label(('object', 'fire hydrant'), related=('street',)),
  Label(('object', 'stop sign'), related=('street',)),
  Label(('object', 'parking meter'), related=('street',)),
  Label(('object', 'bench')),
  Label(('animal', 'bird')),
  Label(('animal', 'mammal', 'cat'), related=('pet',)),
  Label(('animal', 'mammal', 'dog'), related=('pet',)),
  Label(('animal', 'mammal', 'horse')),
  Label(('animal', 'mammal', 'sheep')),
  Label(('animal', 'mammal', 'cow')),
  Label(('animal', 'mammal', 'elephant')),
  Label(('animal', 'mammal', 'bear')),
  Label(('animal', 'mammal', 'zebra')),
  Label(('animal', 'mammal', 'giraffe')),
  Label(('object', 'backpack')),
  Label(('object', 'umbrella'), related=('rain',)),
  Label(('object', 'bag', 'handbag')),
  Label(('object', 'clothing', 'tie')),
  Label(('object', 'suitcase')),
  Label(('object', 'sports', 'frisbee')),
  Label(('object', 'sports', 'skis')),
  Label(('object', 'sports', 'snowboard'), related=('winter', 'skis')),
  Label(('object' 'sports', 'ball')),
  Label(('object', 'sports', 'kite')),
  Label(('object', 'sports', 'baseball bat')),
  Label(('object', 'sports', 'baseball glove')),
  Label(('object', 'sports', 'skateboard')),
  Label(('object', 'sports', 'surfboard')),
  Label(('object', 'sports', 'tennis racket')),
  Label(('object', 'bottle')),
  Label(('object', 'dish', 'glass', 'wine glass')),
  Label(('object', 'dish', 'cup')),
  Label(('object', 'utensil', 'fork')),
  Label(('object', 'utensil', 'knife')),
  Label(('object', 'utensil', 'spoon')),
  Label(('object', 'dish', 'bowl')),
  Label(('food', 'fruit', 'banana')),
  Label(('food', 'fruit', 'apple')),
  Label(('food', 'sandwich')),
  Label(('food', 'fruit', 'orange')),
  Label(('food', 'vegetable', 'broccoli')),
  Label(('food', 'vegetable', 'carrot')),
  Label(('food', 'hot dog')),
  Label(('food', 'pizza')),
  Label(('food', 'dessert', 'donut')),
  Label(('food', 'dessert', 'cake')),
  Label(('object', 'furniture', 'chair')),
  Label(('object', 'furniture', 'couch')),
  Label(('object', 'furniture', 'decoration', 'potted plant')),
  Label(('object', 'furniture', 'bed'), related=('bedroom',)),
  Label(('object', 'furniture', 'dining table')),
  Label(('object', 'fixture', 'toilet'), related=('bathroom',)),
  Label(('object', 'technology', 'television'), alt=('tv',)),
  Label(('object', 'technology', 'laptop')),
  Label(('object', 'technology', 'mouse')),
  Label(('object', 'technology', 'remote')),
  Label(('object', 'technology', 'keyboard')),
  Label(('object', 'technology', 'cell phone'), alt=('phone', 'mobile phone')),
  Label(('object', 'appliance', 'microwave')),
  Label(('object', 'appliance', 'oven')),
  Label(('object', 'appliance', 'toaster')),
  Label(('object', 'fixture', 'sink')),
  Label(('object', 'appliance', 'refrigerator')),
  Label(('object', 'book')),
  Label(('object', 'technology', 'clock')),
  Label(('object', 'furniture', 'decoration', 'vase')),
  Label(('object', 'tool', 'scissors')),
  Label(('object', 'teddy bear')),
  Label(('object', 'appliance', 'hair drier')),
  Label(('object', 'toothbrush')),
]

Coco = Dataset('COCO 2017')
Coco.register(coco_labels)
